### ISSUE TITLE
Add readthedocs configuration

### ISSUE THREAD

**Issue by moshez** [moshez/python-standard#5]
`.readthedocs.yaml`:

```
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
   configuration: doc/conf.py

python:
   install:
   - requirements: requirements-docs.txt
   - method: pip
     path: .
```
